//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GioiThieuSanPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public int ID { get; set; }
        public string EMAIL { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public Nullable<bool> CHUADMIN { get; set; }
    }
}
