//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GioiThieuSanPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSANPHAM
    {
        public int ID { get; set; }
        public Nullable<int> IDSANPHAM { get; set; }
        public string HINHANH { get; set; }
        public Nullable<int> STT { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
