//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GioiThieuSanPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETSANPHAMs = new HashSet<CHITIETSANPHAM>();
            this.TIMHIEUSANPHAMs = new HashSet<TIMHIEUSANPHAM>();
        }
    
        public int ID { get; set; }
        public string TENSANPHAM { get; set; }
        public Nullable<int> MADM { get; set; }
        public string HANGSX { get; set; }
        public string MOTA { get; set; }
        public string MOTA2 { get; set; }
        public string HINHDAIDIEN { get; set; }
        public Nullable<double> GIABAN { get; set; }
        public Nullable<double> GIAKHUYENMAI { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<bool> SANPHAMMOI { get; set; }
        public Nullable<bool> SANPHAMBANCHAY { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public string TENKHONGDAU { get; set; }
    
        public virtual DANHMUC DANHMUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETSANPHAM> CHITIETSANPHAMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMHIEUSANPHAM> TIMHIEUSANPHAMs { get; set; }
    }
}
