//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GioiThieuSanPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMHIEUSANPHAM
    {
        public int ID { get; set; }
        public Nullable<int> MASP { get; set; }
        public string hoten { get; set; }
        public Nullable<int> sdt { get; set; }
        public string EMAIL { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
